# Make Data Ready

In [69]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
%matplotlib inline

In [70]:
df=pd.read_csv('data/car-sales-extended.csv')
df.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [71]:
df.columns


Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [72]:
x=df.drop('Price',axis=1)
y=df['Price']


In [5]:
from sklearn.model_selection import train_test_split

In [6]:
x_train,y_train,x_test,y_test=train_test_split(x,y,test_size=.2)

In [7]:
x_train.shape,y_train.shape,x_test.shape,y_test.shape

((800, 4), (200, 4), (800,), (200,))

In [8]:
from sklearn.ensemble import RandomForestRegressor

clf=RandomForestRegressor(n_estimators=100)

In [9]:
clf.fit(x_train,y_train)

ValueError: could not convert string to float: 'Honda'

In [10]:
# Turn the categories (Make and Colour) into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]
one_hot = OneHotEncoder()
transformer = ColumnTransformer([("one_hot", 
                                 one_hot, 
                                 categorical_features)],
                                 remainder="passthrough")
transformed_X = transformer.fit_transform(x)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [11]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features=['Make','Colour','Doors']
one_hot=OneHotEncoder()

transformer=ColumnTransformer([("one_hot",
                               one_hot,
                               categorical_features)],
                             remainder='passthrough')
transformed_x=transformer.fit_transform(x)


In [12]:
transformed_x[0]

array([0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
       1.0000e+00, 0.0000e+00, 3.5431e+04])

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_features=['Make','Colour','Doors']
one_hot=OneHotEncoder()

transformer=ColumnTransformer([('one_hot',
                               one_hot,
                               categorical_features)],
                             remainder='passthrough')
transtormed_x=transformer.fit_transform(x)
transformed_x[0]

array([0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
       1.0000e+00, 0.0000e+00, 3.5431e+04])

In [14]:
dummies = pd.get_dummies(df[["Make", "Colour", "Doors"]])


In [15]:
df["Doors"] = df["Doors"].astype(object)
dummies = pd.get_dummies(df[["Make", "Colour", "Doors"]])
dummies.head()

Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  Colour_Blue  \
0         0           1            0            0             0            0   
1         1           0            0            0             0            1   
2         0           1            0            0             0            0   
3         0           0            0            1             0            0   
4         0           0            1            0             0            1   

   Colour_Green  Colour_Red  Colour_White  Doors_3  Doors_4  Doors_5  
0             0           0             1        0        1        0  
1             0           0             0        0        0        1  
2             0           0             1        0        1        0  
3             0           0             1        0        1        0  
4             0           0             0        1        0        0

In [16]:
df['Doors'].dtype

dtype('O')

In [17]:
x["Make"].value_counts()

Toyota    398
Honda     304
Nissan    198
BMW       100
Name: Make, dtype: int64

In [18]:
# Let's refit the model
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X,
                                                    y,
                                                    test_size=0.2)

model.fit(X_train, y_train)

NameError: name 'model' is not defined

In [19]:
np.random.seed(42)
x_train,x_test,y_train,y_test=train_test_split(transformed_x,y,test_size=.2)
clf.fit(x_train,y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [20]:
clf.score(X_test, y_test)

0.3235867221569877

In [21]:
#Another way to show numerical value for every row column
dummies=pd.get_dummies(df[['Make','Colour','Doors']])
dummies.head()

Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  Colour_Blue  \
0         0           1            0            0             0            0   
1         1           0            0            0             0            1   
2         0           1            0            0             0            0   
3         0           0            0            1             0            0   
4         0           0            1            0             0            1   

   Colour_Green  Colour_Red  Colour_White  Doors_3  Doors_4  Doors_5  
0             0           0             1        0        1        0  
1             0           0             0        0        0        1  
2             0           0             1        0        1        0  
3             0           0             1        0        1        0  
4             0           0             0        1        0        0

In [22]:
car_sales_missing=pd.read_csv('data/car-sales-extended-missing-data.csv')
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [23]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [24]:
car_sales_missing['Make'].fillna('Missing',inputlace=True)

TypeError: fillna() got an unexpected keyword argument 'inputlace'

In [25]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [26]:
car_sales_missing['Colour'].fillna('Missing',inplace=True)
car_sales_missing['Odometer (KM)'].fillna(car_sales_missing['Odometer (KM)'].mean(),inplace=True)

In [27]:
car_sales_missing.isna().sum()

Make             49
Colour            0
Odometer (KM)     0
Doors            50
Price            50
dtype: int64

In [28]:
car_sales_missing['Doors'].fillna(car_sales_missing['Doors'].mean(),inplace=True)

In [29]:
car_sales_missing.dropna(inplace=True)

In [30]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_fetures=['Make','Colour','Doors']

one_hot=OneHotEncoder()

transformer=ColumnTransformer([('one_hot',
                               one_hot,
                               categorical_fetures)],
                             remainder='passthrough')
transform_x=transformer.fit_transform(car_sales_missing)
transform_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

In [33]:
df.head()

Make Colour  Odometer (KM) Doors  Price
0   Honda  White          35431     4  15323
1     BMW   Blue         192714     5  19943
2   Honda  White          84714     4  28343
3  Toyota  White         154365     4  13434
4  Nissan   Blue         181577     3  14043

In [34]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [35]:
# Reimport the DataFrame

car_sales_missing=pd.read_csv('data/car-sales-extended-missing-data.csv')
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [36]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [39]:
car_sales_missing.dropna(subset=['Price'],inplace=True)

In [40]:
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [41]:
x=car_sales_missing.drop('Price',axis=1)
y=car_sales_missing['Price']

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2)

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [43]:
categorical_imputer=SimpleImputer(strategy='constant',fill_value='missing')
number_imputer=SimpleImputer(strategy='mean')
door_imputer=SimpleImputer(strategy='constant',fill_value=4)

In [47]:
categorical_features=['Make','Colour']
door_features=['Doors']
numerical_features=['Odometer (KM)']

In [48]:
imputer=ColumnTransformer([('categorical_imputer',categorical_imputer,categorical_features),
                          ('number_imputer',number_imputer,numerical_features),
                          ('door_imputer',door_imputer,door_features)])

In [49]:
T_x_train=imputer.fit_transform(x_train)
T_x_test=imputer.fit_transform(x_test)

In [50]:
T_x_train

array([['Toyota', 'Black', 86696.0, 4.0],
       ['Toyota', 'Black', 20714.0, 4.0],
       ['Toyota', 'White', 134415.0, 4.0],
       ...,
       ['Honda', 'Blue', 224900.0, 4.0],
       ['missing', 'White', 19482.0, 3.0],
       ['Honda', 'Blue', 199833.0, 4.0]], dtype=object)

In [51]:
car_sales_filled_x_train=pd.DataFrame(T_x_train, columns=["Make", "Colour", "Doors", "Odometer (KM)"])

In [53]:
car_sales_filled_x_train.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [54]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [56]:
car_sales_missing.head(1)

Make Colour  Odometer (KM)  Doors    Price
0  Honda  White        35431.0    4.0  15323.0

In [57]:
categorical_fet=['Make','Colour']
number_fet=['Odometer (KM)']
door_fet=['Doors']

categorical_imputer=SimpleImputer(strategy='constant',fill_value='Missing')
number_imputer=SimpleImputer(strategy='mean')
door_imputer=SimpleImputer(strategy='most_frequent')

transformer=ColumnTransformer([
    ('categorical_imputer',categorical_imputer,categorical_fet),
    ('number_imputer',number_imputer,number_fet),
    ('door_imputer',door_imputer,door_fet)
])


In [61]:
tra_x_train=transformer.fit_transform(x_train)
tra_x_train

array([['Toyota', 'Black', 86696.0, 4.0],
       ['Toyota', 'Black', 20714.0, 4.0],
       ['Toyota', 'White', 134415.0, 4.0],
       ...,
       ['Honda', 'Blue', 224900.0, 4.0],
       ['Missing', 'White', 19482.0, 3.0],
       ['Honda', 'Blue', 199833.0, 4.0]], dtype=object)

In [64]:
transform_x_train=pd.DataFrame(tra_x_train, columns=['Make','Colour','Odometer (KM)','Doors'])

In [65]:
transform_x_train.head()

Make Colour Odometer (KM) Doors
0  Toyota  Black         86696     4
1  Toyota  Black         20714     4
2  Toyota  White        134415     4
3  Toyota  Green        130710     4
4   Honda  White        145850     4

In [68]:
transform_x_train.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
dtype: int64