In [69]:
import numpy as np
import pandas as pd

In [71]:
np.random.seed(0)
sales_amount=np.random.randint(20,size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [72]:
weekly_sales=pd.DataFrame(sales_amount,index=['Mon','Tues','Wed','Thurs','Fry'],
                         columns=['Almond butter','Peanut butter','Cashew butter'])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fry                1              6              7

In [75]:
price=np.array([10,8,12])
price.shape

(3,)

In [76]:
butter_prices=pd.DataFrame(price.reshape(1,3),index=['Price'],columns=['Almod butter','Peanut butter','Cashew butter'])
butter_prices

Almod butter  Peanut butter  Cashew butter
Price            10              8             12

In [77]:
sales_amount=butter_prices.dot(weekly_sales.T)

ValueError: matrices are not aligned

In [80]:
total_sales=price.dot(sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [81]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [87]:
weekly=weekly_sales.T
weekly


Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fry                1              6              7

In [95]:
butter_prices.shape, weekly_sales.shape

((1, 3), (3, 5))

In [97]:
x=butter_prices.dot(np.random.randint(6,size=(3,5)))
x

0   1   2   3   4
Price  24  34  86  94  74

In [100]:
butter_prices.dot(sales_amount.T)

0    1    2    3    4
Price  240  138  458  232  142

In [103]:
sales_amount.T

array([[12,  3,  9,  4,  1],
       [15,  3, 19,  6,  6],
       [ 0,  7, 18, 12,  7]])

In [102]:
weekly_sales

Mon  Tues  Wed  Thurs  Fry
Almond butter   12     3    9      4    1
Peanut butter   15     3   19      6    6
Cashew butter    0     7   18     12    7