# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [44]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [45]:
# Create a 1-dimensional NumPy array using np.array()
one=np.array([23,4,5,6,7])
one

# Create a 2-dimensional NumPy array using np.array()

two=np.array([
    [1,32,4,5,5],
    [3,4,5,6,3],
    [3,4,5,3,3],
])

two

# Create a 3-dimensional Numpy array using np.array()
three=np.array([[[1,2,3],[3,4,5],[3,4,3],[3,3,3]]])
three
three.shape
three.ndim

3

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [46]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

two.shape
two.ndim
two.dtype
two.size

15

In [47]:
# Attributes of 2-dimensional array


In [48]:
# Attributes of 3-dimensional array


In [49]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

random_array=np.random.randint(20,size=(3,3))

df=pd.DataFrame(random_array,index=['bangla','english','math'],columns=['hadi','mantasha','fariha'])
df


hadi  mantasha  fariha
bangla     16         7       2
english     2         0       4
math        9         6       8

In [50]:
# Create an array of shape (10, 2) with only ones
two.reshape(5,3)

array([[ 1, 32,  4],
       [ 5,  5,  3],
       [ 4,  5,  6],
       [ 3,  3,  4],
       [ 5,  3,  3]])

In [51]:
# Create an array of shape (7, 2, 3) of only zeros
arr=np.random.randint(10,size=(7,2,3))
arr

array([[[6, 8, 7],
        [1, 0, 6]],

       [[6, 7, 4],
        [2, 7, 5]],

       [[2, 0, 2],
        [4, 2, 0]],

       [[4, 9, 6],
        [6, 8, 9]],

       [[9, 2, 6],
        [0, 3, 3]],

       [[4, 6, 6],
        [3, 6, 2]],

       [[5, 1, 9],
        [8, 4, 5]]])

In [52]:
# Create an array within a range of 0 and 100 with step 3
newar=np.arange(0,100,3)
newar

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [53]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(10,size=(7,2))

array([[3, 9],
       [6, 8],
       [6, 0],
       [0, 8],
       [8, 3],
       [8, 2],
       [6, 5]])

In [54]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.randint(1,size=(3,5),dtype='int32')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [55]:
# Set the random seed to 42
np.random.seed(42)
np.random.randint(10,size=(4,6))

# Create a random array of numbers between 0 & 10 of size (4, 6)


array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [56]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
ar=np.random.randint(10,size=(3,7))
np.unique(ar)

# Find the unique numbers in the array you just created


array([0, 1, 2, 3, 4, 6, 8, 9])

In [95]:
# Find the 0'th index of the latest array you created
ar[0]

array([8, 0, 9, 2, 6, 3, 8])

In [99]:
# Get the first 2 rows of latest array you created
print(ar)
ar[0:2:]

[[8 0 9 2 6 3 8]
 [2 4 2 6 4 8 6]
 [1 3 8 1 9 8 9]]


array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [108]:
# Get the first 2 values of the first 2 rows of the latest array
ar[0:2:]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [60]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables


In [109]:
# Add the two arrays together
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
a+b

array([5, 5, 5, 5])

In [124]:
# Create another array of ones of shape (5, 3)
x=np.ones(shape=(3,5))

In [125]:
# Try add the array of ones and the other most recent array together
ar+x

ValueError: operands could not be broadcast together with shapes (3,7) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [129]:
# Create another array of ones of shape (3, 5)
another=np.ones(shape=(3,5))

In [130]:
# Subtract the new array of ones from the other most recent array
x-another

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [132]:
# Multiply the ones array with the latest array
latest=x*another

In [133]:
# Take the latest array to the power of 2 using '**'
latest**2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [134]:
# Do the same thing with np.square()
np.square(latest)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [135]:
# Find the mean of the latest array using np.mean()
np.mean(ar)

5.095238095238095

In [136]:
# Find the maximum of the latest array using np.max()
np.max(ar)

9

In [137]:
# Find the minimum of the latest array using np.min()
np.min(ar)

0

In [138]:
# Find the standard deviation of the latest array


In [139]:
# Find the variance of the latest array
np.var(ar)

9.038548752834467

In [140]:
# Reshape the latest array to (3, 5, 1)
ar.reshape(3,5,1)

ValueError: cannot reshape array of size 21 into shape (3,5,1)

In [75]:
# Transpose the latest array


What does the transpose do?

In [145]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
m=np.random.randint(10,size=(3,3))
n=np.random.randint(10,size=(3,2))

In [150]:
# Perform a dot product on the two newest arrays you created
m.dot(n)

array([[ 70, 120],
       [ 73,  40],
       [104, 136]])

In [153]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a=np.random.randint(10,size=(4,3))
b=np.random.randint(10,size=(4,3))


In [155]:
# Perform a dot product on the two newest arrays you created
b.dot(a.T)

array([[114,  58,  48, 180],
       [ 56,   7,  14,  69],
       [ 98,  56,  40, 153],
       [ 56,  28,  36, 111]])

It doesn't work. How would you fix it?

In [80]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [156]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
s=np.random.randint(10,size=(2,3))
t=np.random.randint(10,size=(2,3))


In [157]:
# Compare the two arrays with '>'
s>t

array([[ True, False, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [158]:
# Compare the two arrays with '>='
s>=t

array([[ True, False, False],
       [False, False, False]])

In [166]:
# Find which elements of the first array are greater than 7
s[s>7]

array([], dtype=int32)

In [168]:
# Which parts of each array are equal? (try using '==')
print(s)
s[s==s]

[[5 2 0]
 [2 4 2]]


array([5, 2, 0, 2, 4, 2])

In [170]:
# Sort one of the arrays you just created in ascending order
np.sort(s)

array([[0, 2, 5],
       [2, 2, 4]])

In [172]:
# Sort the indexes of one of the arrays you just created
np.argsort(s)

array([[2, 1, 0],
       [0, 2, 1]], dtype=int64)

In [174]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(s)

0

In [175]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(s)

2

In [176]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmin(s,axis=1)

array([2, 0], dtype=int64)

In [177]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(s,axis=0)

array([1, 0, 0], dtype=int64)

In [181]:
# Create an array of normally distributed random numbers
np.random.rand(2,3)

array([[0.56327557, 0.69551609, 0.13933145],
       [0.60441738, 0.53984109, 0.20306122]])

In [93]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.